name: hexcolor
description: Brings HexColor for your dart and flutter projects, convert material colors to hex colors
version: 3.0.2
homepage: https://github.com/ggichure/hexcolor

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  lints: ^6.0.0
  test: ^1.16.0
  flutter_test:
    sdk: flutter
